// action types
export const SECTOR_MATERIALS_REQUEST = "SECTOR_MATERIALS_REQUEST";
export const SECTOR_MATERIALS_SUCCESS = "SECTOR_MATERIALS_SUCCESS";
export const SECTOR_MATERIALS_FAILURE = "SECTOR_MATERIALS_FAILURE";
export const SECTOR_MATERIALS_RESET = "SECTOR_MATERIALS_RESET";

export const SECTOR_HEALTH_CARE_REQUEST = "SECTOR_HEALTH_CARE_REQUEST";
export const SECTOR_HEALTH_CARE_SUCCESS = "SECTOR_HEALTH_CARE_SUCCESS";
export const SECTOR_HEALTH_CARE_FAILURE = "SECTOR_HEALTH_CARE_FAILURE";
export const SECTOR_HEALTH_CARE_RESET = "SECTOR_HEALTH_CARE_RESET";

export const SECTOR_TECHNOLOGY_REQUEST = "SECTOR_TECHNOLOGY_REQUEST";
export const SECTOR_TECHNOLOGY_SUCCESS = "SECTOR_TECHNOLOGY_SUCCESS";
export const SECTOR_TECHNOLOGY_FAILURE = "SECTOR_TECHNOLOGY_FAILURE";
export const SECTOR_TECHNOLOGY_RESET = "SECTOR_TECHNOLOGY_RESET";

export const SECTOR_FINANCIALS_REQUEST = "SECTOR_FINANCIALS_REQUEST";
export const SECTOR_FINANCIALS_SUCCESS = "SECTOR_FINANCIALS_SUCCESS";
export const SECTOR_FINANCIALS_FAILURE = "SECTOR_FINANCIALS_FAILURE";
export const SECTOR_FINANCIALS_RESET = "SECTOR_FINANCIALS_RESET";

export const SECTOR_INDUSTRIALS_REQUEST = "SECTOR_INDUSTRIALS_REQUEST";
export const SECTOR_INDUSTRIALS_SUCCESS = "SECTOR_INDUSTRIALS_SUCCESS";
export const SECTOR_INDUSTRIALS_FAILURE = "SECTOR_INDUSTRIALS_FAILURE";
export const SECTOR_INDUSTRIALS_RESET = "SECTOR_INDUSTRIALS_RESET";

export const SECTOR_ENERGY_REQUEST = "SECTOR_ENERGY_REQUEST";
export const SECTOR_ENERGY_SUCCESS = "SECTOR_ENERGY_SUCCESS";
export const SECTOR_ENERGY_FAILURE = "SECTOR_ENERGY_FAILURE";
export const SECTOR_ENERGY_RESET = "SECTOR_ENERGY_RESET";

export const SECTOR_CONSUMER_STAPLES_REQUEST = "SECTOR_CONSUMER_STAPLES_REQUEST";
export const SECTOR_CONSUMER_STAPLES_SUCCESS = "SECTOR_CONSUMER_STAPLES_SUCCESS";
export const SECTOR_CONSUMER_STAPLES_FAILURE = "SECTOR_CONSUMER_STAPLES_FAILURE";
export const SECTOR_CONSUMER_STAPLES_RESET = "SECTOR_CONSUMER_STAPLES_RESET";

export const SECTOR_REAL_ESTATE_REQUEST = "SECTOR_REAL_ESTATE_REQUEST";
export const SECTOR_REAL_ESTATE_SUCCESS = "SECTOR_REAL_ESTATE_SUCCESS";
export const SECTOR_REAL_ESTATE_FAILURE = "SECTOR_REAL_ESTATE_FAILURE";
export const SECTOR_REAL_ESTATE_RESET = "SECTOR_REAL_ESTATE_RESET";

export const SECTOR_CONSUMER_DISCRETIONARY_REQUEST = "SECTOR_CONSUMER_DISCRETIONARY_REQUEST";
export const SECTOR_CONSUMER_DISCRETIONARY_SUCCESS = "SECTOR_CONSUMER_DISCRETIONARY_SUCCESS";
export const SECTOR_CONSUMER_DISCRETIONARY_FAILURE = "SECTOR_CONSUMER_DISCRETIONARY_FAILURE";
export const SECTOR_CONSUMER_DISCRETIONARY_RESET = "SECTOR_CONSUMER_DISCRETIONARY_RESET";

export const SECTOR_UTILITIES_REQUEST = "SECTOR_UTILITIES_REQUEST";
export const SECTOR_UTILITIES_SUCCESS = "SECTOR_UTILITIES_SUCCESS";
export const SECTOR_UTILITIES_FAILURE = "SECTOR_UTILITIES_FAILURE";
export const SECTOR_UTILITIES_RESET = "SECTOR_UTILITIES_RESET";

export const SECTOR_COMMUNICATION_SERVICES_REQUEST = "SECTOR_COMMUNICATION_SERVICES_REQUEST";
export const SECTOR_COMMUNICATION_SERVICES_SUCCESS = "SECTOR_COMMUNICATION_SERVICES_SUCCESS";
export const SECTOR_COMMUNICATION_SERVICES_FAILURE = "SECTOR_COMMUNICATION_SERVICES_FAILURE";
export const SECTOR_COMMUNICATION_SERVICES_RESET = "SECTOR_COMMUNICATION_SERVICES_RESET";

export const SECTORS_REQUEST = "SECTORS_REQUEST";
export const SECTORS_SUCCESS = "SECTORS_SUCCESS";
export const SECTORS_FAILURE = "SECTORS_FAILURE";
export const SECTORS_RESET = "SECTORS_RESET";

export const API_DETAILED_MOST_ACTIVE_REQUEST = "API_DETAILED_MOST_ACTIVE_REQUEST"
export const API_DETAILED_MOST_ACTIVE_SUCCESS = "API_DETAILED_MOST_ACTIVE_SUCCESS"
export const API_DETAILED_MOST_ACTIVE_FAILURE = "API_DETAILED_MOST_ACTIVE_FAILURE"
export const API_DETAILED_MOST_ACTIVE_RESET = "API_DETAILED_MOST_ACTIVE_RESET"

export const API_DETAILED_GAINERS_REQUEST = "API_DETAILED_GAINERS_REQUEST"
export const API_DETAILED_GAINERS_SUCCESS = "API_DETAILED_GAINERS_SUCCESS"
export const API_DETAILED_GAINERS_FAILURE = "API_DETAILED_GAINERS_FAILURE"
export const API_DETAILED_GAINERS_RESET = "API_DETAILED_GAINERS_RESET"

export const API_DETAILED_LOSERS_REQUEST = "API_DETAILED_LOSERS_REQUEST"
export const API_DETAILED_LOSERS_SUCCESS = "API_DETAILED_LOSERS_SUCCESS"
export const API_DETAILED_LOSERS_FAILURE = "API_DETAILED_LOSERS_FAILURE"
export const API_DETAILED_LOSERS_RESET = "API_DETAILED_LOSERS_RESET"


export const IEX_MOST_ACTIVE_REQUEST = "IEX_MOST_ACTIVE_REQUEST"
export const IEX_MOST_ACTIVE_SUCCESS = "IEX_MOST_ACTIVE_SUCCESS"
export const IEX_MOST_ACTIVE_FAILURE = "IEX_MOST_ACTIVE_FAILURE"
export const IEX_MOST_ACTIVE_RESET = "IEX_MOST_ACTIVE_RESET"

export const IEX_GAINERS_REQUEST = "IEX_GAINERS_REQUEST"
export const IEX_GAINERS_SUCCESS = "IEX_GAINERS_SUCCESS"
export const IEX_GAINERS_FAILURE = "IEX_GAINERS_FAILURE"
export const IEX_GAINERS_RESET = "IEX_GAINERS_RESET"

export const IEX_LOSERS_REQUEST = "IEX_LOSERS_REQUEST"
export const IEX_LOSERS_SUCCESS = "IEX_LOSERS_SUCCESS"
export const IEX_LOSERS_FAILURE = "IEX_LOSERS_FAILURE"
export const IEX_LOSERS_RESET = "IEX_LOSERS_RESET"

export const IEX_SECTOR_OVERVIEW_REQUEST = "IEX_SECTOR_OVERVIEW_REQUEST"
export const IEX_SECTOR_OVERVIEW_SUCCESS = "IEX_SECTOR_OVERVIEW_SUCCESS"
export const IEX_SECTOR_OVERVIEW_FAILURE = "IEX_SECTOR_OVERVIEW_FAILURE"
export const IEX_SECTOR_OVERVIEW_RESET = "IEX_SECTOR_OVERVIEW_RESET"